global:
  dnsSuffix: .local
  appName: app-desafio
  namespace: dev

env: dev 

dependenciesOnly: false

minReplicas: 1
maxReplicas: 5
targetCPU: 80
targetMemory: 90

progressDeadlineSeconds: 200
terminationGracePeriodSeconds: 60


image:
  repository: app
  tag: latest
  pullPolicy: Always

service:
  port: 80
  protocol: http
  additionalPorts: {}

pod:
  annotations: |

ingress:
  enabled: true
  annotations: {

          nginx.ingress.kubernetes.io/rewrite-target: /$1
 }
  additionalRules: {}

environmentVariables: {}

readinessProbe: |-
  tcpSocket:
    port: {{ .Values.service.port }}
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe: |-
  tcpSocket:
    port: {{ .Values.service.port }}
  initialDelaySeconds: 120
  periodSeconds: 10

resources: {}
lifecycle: {}
nodeSelector: {}
tolerations: []

affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: "failure-domain.beta.kubernetes.io/zone"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "{{ .Values.global.appName }}"
    - weight: 99
      podAffinityTerm:
        topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "{{ .Values.global.appName }}"
